### ISSUE TITLE
Compiling on OS X gave me 2 errors, 1 note, 1 warning..

### ISSUE THREAD

**Issue by m4ddav3** [Elbagast/TF2_Mod_Builder#4]
```
../TF2_Mod_Builder/saklib/type_traits.h:36:15: error: call to deleted constructor of 'stored_type' (aka 'Saklib::Undefined')
                    value = stored_type();
                            ^
../TF2_Mod_Builder/saklib/types.h:23:3: note: 'Undefined' has been explicitly marked deleted here
                Undefined() = delete;
                ^
../TF2_Mod_Builder/saklib/attribute_definition.h:53:42: error: unknown type name 'Attribute_Definition_Type'
                return Shptr<Attribute_Definition>(new Attribute_Definition_Type<TypeHolder_st<TE> >(name));
                                                       ^
../TF2_Mod_Builder/saklib/attribute_definition.h:51:77: warning: unused parameter 'name' [-Wunused-parameter]
        Shptr<Attribute_Definition> make_shared_Attribute_Definition(String const& name)
                                                                                   ^
```

**Comment by Elbagast** [comment]
These seem to all be coming from one function that isn't even used...in fact it looks like something I forgot to remove from a while ago. The Visual Studio compiler is completely ignoring the function because it's a template and is unused.

The first and second errors look like your compiler is handing enumerated templates a bit differently. Or not? I can't remember if I actually used this function, it might have never actually been compiled...

Comment out / delete the function on lines 50-54 in TF2_Mod_Builder/saklib/attribute_definition.h and see if that gets rid of this.

**Comment by Elbagast** [comment]
I've merged the branch I've been working on into master with a bunch of edits to clean up compiler warnings - there aren't any on MSVC 2013 now. Does that fix things at your end?

**Comment by m4ddav3** [comment]
Now that you've got it compiling on MinGW, can you publish a branch with your fixes for me to try on my Macbook?

**Comment by Elbagast** [comment]
a7a9d16b49246efb0bf25a3f0a2949e3464fe945 has all the cleanup I've done for this.

**Comment by Elbagast** [comment]
This is waaaaaay out of date now.
